version: "3.9"

services:
  # -------------------------
  # 1. Apache Airflow
  # -------------------------
  airflow:
    image: apache/airflow:2.6.3
    container_name: airflow-demo
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__FERNET_KEY=ukFVBNBcN97a4WjO-ZEZVd51FVuXQlU42y7EYYqr-vc=
    volumes:
      - ./airflow_dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
    ports:
      - "8080:8080"
    networks:
      - mlops-network
    command: >
      bash -c "
      airflow db init &&
      (airflow users create --username admin --firstname Admin --lastname User --role Admin --email admin@example.com --password admin || echo 'User exists') &&
      airflow webserver
      "
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://airflow-demo:8080/health || exit 1"]
      interval: 10s
      retries: 10
      timeout: 5s
    restart: unless-stopped

  # -------------------------
  # 2. MLflow Tracking Server
  # -------------------------
  mlflow:
    build:
      context: .
      dockerfile: mlflow_server/Dockerfile
    container_name: mlflow-demo
    volumes:
      - mlflow_artifacts:/mlflow_artifacts
    ports:
      - "5000:5000"
    networks:
      - mlops-network
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow-demo:5000
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://mlflow-demo:5000/api/2.0/mlflow/experiments/list || exit 1"]
      interval: 5s
      retries: 12
      timeout: 5s
    restart: unless-stopped

  # -------------------------
  # 3. Model Service API
  # -------------------------
  model-service:
    build:
      context: .
      dockerfile: model_service/Dockerfile
    container_name: model-service-demo
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./artifacts:/app/artifacts
    depends_on:
      - mlflow
    environment:
      - MLFLOW_TRACKING_URI=http://mlflow-demo:5000
    networks:
      - mlops-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://model-service-demo:8000/health || exit 1"]
      interval: 5s
      retries: 12
      timeout: 5s
    restart: unless-stopped

  # -------------------------
  # 4. Jenkins CI/CD Server
  # -------------------------
  jenkins:
    build:
      context: .
      dockerfile: jenkins/Dockerfile
    container_name: jenkins-demo
    ports:
      - "8081:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - mlflow_artifacts:/mlflow_artifacts
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
      - JENKINS_OPTS=--prefix=/jenkins
      - MLFLOW_TRACKING_URI=http://mlflow-demo:5000
    depends_on:
      - model-service
      - mlflow
      - prometheus
      - grafana
    networks:
      - mlops-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://jenkins-demo:8080/login || exit 1"]
      interval: 10s
      retries: 10
      timeout: 5s
    restart: unless-stopped

  # -------------------------
  # 5. Prometheus for metrics
  # -------------------------
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-demo
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - mlops-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://prometheus-demo:9090/metrics || exit 1"]
      interval: 5s
      retries: 12
      timeout: 5s
    restart: unless-stopped

  # -------------------------
  # 6. Grafana for visualization
  # -------------------------
  grafana:
    image: grafana/grafana:latest
    container_name: grafana-demo
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./grafana/dashboard.json:/tmp/dashboard.json
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    networks:
      - mlops-network
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://grafana-demo:3000/api/health || exit 1"]
      interval: 5s
      retries: 12
      timeout: 5s
    restart: unless-stopped

# -------------------------
# Docker network
# -------------------------
networks:
  mlops-network:
    driver: bridge

# -------------------------
# Volumes for persistence
# -------------------------
volumes:
  mlflow_artifacts:
  jenkins_home:
  grafana-storage:
  artifacts:
