
pipeline {
  agent any
  stages {
    stage('Checkout') {
      steps {
        checkout scm
      }
    }
    stage('Run DVC repro') {
      steps {
        sh 'dvc repro || true'
      }
    }
    stage('Build & Push') {
      steps {
        sh 'docker-compose build'
      }
    }
  }
}
